sonar.projectKey=fastapi_app
sonar.projectName=FastAPI App
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000

sonar.python.coverage.reportPaths=coverage.xml

# html 내부의 js 코드 및 커버리지 미수집 테스트 파일 분석에서 제외
sonar.exclusions=**/*.js,**/*.css,**/*.html,tests/test_ui.py,tests/test_deployed_api.py